# fly.toml app configuration file generated for sly-cli on 2023-07-18T01:30:32+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sly-cli"
primary_region = "mad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
